# permissions for end users to edit exposeapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: exposeapp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: expose-traffic-outside-cluster-operator
    app.kubernetes.io/part-of: expose-traffic-outside-cluster-operator
    app.kubernetes.io/managed-by: kustomize
  name: exposeapp-editor-role
rules:
- apiGroups:
  - expose-traffic-outside-cluster.bailu.io
  resources:
  - exposeapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - expose-traffic-outside-cluster.bailu.io
  resources:
  - exposeapps/status
  verbs:
  - get
